# Generated by Django 4.0.3 on 2022-12-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_ticket_history_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=30)),
                ('userid', models.DecimalField(decimal_places=0, max_digits=2)),
                ('busid', models.DecimalField(decimal_places=0, max_digits=2)),
                ('bus_name', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=30)),
                ('dest', models.CharField(max_length=30)),
                ('nos', models.DecimalField(decimal_places=0, max_digits=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('B', 'Booked'), ('C', 'Cancelled')], default='B', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='busdetails',
            name='bus_type',
            field=models.CharField(default='AC', max_length=10),
        ),
        migrations.AddField(
            model_name='busdetails',
            name='nos',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='busdetails',
            name='rem',
            field=models.DecimalField(decimal_places=0, default='5', max_digits=2),
        ),
    ]
