# Generated by Django 4.0.3 on 2022-12-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_book_busdetails_bus_type_busdetails_nos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='no_tkt',
            field=models.IntegerField(default='1'),
        ),
    ]
