# Generated by Django 4.0.3 on 2022-12-12 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_customer_no_tkt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='destination_two',
            field=models.ForeignKey(error_messages={'destination_two': 'Enter Your Destination'}, on_delete=django.db.models.deletion.CASCADE, to='app.destination'),
        ),
        migrations.AlterField(
            model_name='route',
            name='origin',
            field=models.CharField(error_messages={'origin': 'Enter Your Origin'}, max_length=200),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=12)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('flag', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
