# Generated by Django 4.0.3 on 2022-12-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_route_destination_two_alter_route_origin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
    ]
