# Generated by Django 4.0.3 on 2022-12-12 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_profile_updated_date_alter_profile_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='destination_two',
            field=models.ForeignKey(error_messages={'destination_two': 'Enter Your Destination'}, on_delete=django.db.models.deletion.CASCADE, related_name='destination_location', to='app.destination'),
        ),
        migrations.AlterField(
            model_name='route',
            name='origin',
            field=models.ForeignKey(error_messages={'origin': 'Enter Your Origin'}, on_delete=django.db.models.deletion.CASCADE, related_name='Origin_location', to='app.destination'),
        ),
    ]
