# Generated by Django 4.0.3 on 2022-12-12 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_route_destination_two_alter_route_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='destination_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Destination_location1', to='app.destination'),
        ),
        migrations.AlterField(
            model_name='busdetails',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Origin_location1', to='app.destination'),
        ),
    ]
