# Generated by Django 4.0.3 on 2022-12-12 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_busdetails_destination_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='destination_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.destination'),
        ),
        migrations.AlterField(
            model_name='busdetails',
            name='source',
            field=models.CharField(max_length=200),
        ),
    ]
