# Generated by Django 4.0.3 on 2022-12-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_profile_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='flag',
            field=models.BooleanField(blank=True),
        ),
    ]
