# Generated by Django 4.0.3 on 2022-12-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_profile_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='flag',
            field=models.BooleanField(null=True),
        ),
    ]
