# Generated by Django 4.0.3 on 2022-12-20 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_profile_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='flag',
        ),
    ]
