# Generated by Django 4.0.3 on 2022-12-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_delete_book_alter_ticket_history_aadhar_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='aadhar_no',
            field=models.IntegerField(null=True),
        ),
    ]
