# Generated by Django 4.0.3 on 2023-01-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_customer_aadhar_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='bus_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='busdetails',
            name='rem',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
