# Generated by Django 4.0.3 on 2023-01-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_busdetails_bus_type_alter_busdetails_rem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='nos',
            field=models.DecimalField(decimal_places=0, default=60, max_digits=2),
        ),
    ]
