# Generated by Django 4.0.3 on 2023-01-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='driver_phono',
            field=models.IntegerField(),
        ),
    ]
